### ISSUE TITLE
Better handling of optional dependencies

### ISSUE THREAD

**Issue by lrustand** [lrustand/qutebrowser.el#12]
Various optional features have dependencies, such as `qutebrowser-pass` depends on password-store, `qutebrowser-launcher` depends on `consult` and `sqlite`, `qutebrowser-theme-export-mode` depends on `color`, etc. I also have an upcoming feature that provides integration with `doom-modeline`. Currently all these dependencies are required directly in the top of the file unconditionally. It would be better to make them optional in some way, but I'm not sure how it is best handled.

Possible ways of handling this:

- Split out packages with specific functionality not directly related to the core package that depends on thirdparty packages.
 - Wrap things in `with-eval-after-load`.
 - Create multiple "features" that can be required at will.
 - Remove usage of `dash` functions.

**Comment by minimaximalist** [comment]
What about splitting out the mentioned features into their own files within this repo, a la Vertico and its extensions?

**Comment by lrustand** [comment]
Yeah, I think that is the best approach. I have already split out the Doom modeline stuff to a separate file since that gave lots trouble with loading when not explicitly requiring the Doom modeline package.

I think I will take the approach that any features that provide optional integration with some third-party package will be in a separate file. I think this makes the dependency handling cleaner and seems to avoid some problems with loading issues that could occur even if the stuff was wrapped inside a `with-eval-after-load`.
