### ISSUE TITLE
SQLite logic error when apostrophe included in launcher query

### ISSUE THREAD

**Issue by minimaximalist** [lrustand/qutebrowser.el#15]
Because the user input to SQLite is not escaped, including an apostrophe (possibly other characters too, I haven't checked) when using `qutebrowser-launcher` causes an error.

**Comment by lrustand** [comment]
Pushed a fix now using parameterized values for the user input. Also fixed potential trouble with special characters in regex in match highlighting and buffer+bookmark search.
