### ISSUE TITLE
Cannot use-package qutebrowser, missing package marginalia

### ISSUE THREAD

**Issue by MarcCoquand** [lrustand/qutebrowser.el#2]
Heya!

Thanks for making this.

When I try to import it:

```
(use-package qutebrowser
  :load-path "site-lisp/qutebrowser")
```

I run into the following

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "marginalia")
  require(marginalia)
  load-with-code-conversion("/home/me/.emacs.d/site-lisp/qutebrowser.el/quteb..." "/home/me/.emacs.d/site-lisp/qutebrowser.el/quteb..." t t)
  require(qutebrowser nil t)
  (not (require 'qutebrowser nil t))
  (if (not (require 'qutebrowser nil t)) (display-warning 'use-package (format "Cannot load %s" 'qutebrowser) :error))
```

It seems the package depends on marginalia to function?

**Comment by lrustand** [comment]
Thanks for the issue! It actually only uses marginalia for one single thing: the face `marginalia-key` used to highlight the titles of the webpages in the URL launcher. This is obviously not crucial, so I went ahead and removed it, changing the face to `font-lock-keyword-face` instead (which the marginalia face was inheriting from). Give it a try now.

**Comment by MarcCoquand** [comment]
I tried it again and now I do not have that issue, thanks!

**Comment by lrustand** [comment]
Ok, great! Please let me know if there are any other issues, or if you have any feature requests!
